const products = [
  {
      id: 1,
      name: 'MacBook Air',
      brand: 'Apple',
      price: 1499,
      image: 'https://d2ihpvt6nd5q28.cloudfront.net/wp-content/uploads/2023/01/macbook-air-midnight-gallery1-20220606.jpeg',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
  {
      id: 2,
      name: 'Inspiron',
      brand: 'Dell',
      price: 1099,
      image: 'https://i.blogs.es/47cce3/captura-de-pantalla-2022-06-23-a-las-10.45.07/1366_2000.jpeg',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
  {
      id: 3,
      name: 'VivoBook',
      brand: 'Asus',
      price: 1099,
      image: 'https://dlcdnwebimgs.asus.com/gain/8240ec93-d4ed-4fdd-8915-8e6d49d8b288/w800',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
  {
      id: 4,
      name: 'Pavilion',
      brand: 'HP',
      price: 999,
      image: 'https://http2.mlstatic.com/D_NQ_NP_927120-MLA44936141849_022021-O.jpg',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
  {
      id: 5,
      name: 'Legion',
      brand: 'IdeaPad',
      price: 1010,
      image: 'https://p4-ofp.static.pub/ShareResource/na/subseries/gallery/lenovo-ideapad-pro-5i-gen8-16inch-1.png',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
  {
      id: 6,
      name: 'Aspire',
      brand: 'Acer',
      price: 999,
      image: 'https://images.acer.com/is/image/acer/acer-aspire-7-a715-51g-A715-76-finger-print-backlit-on-wallpaper-charcoal-black-01-2?$Product-Cards-XL$',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
  {
    id: 7,
    name: 'Modern',
    brand: 'MSI',
    price: 999,
    image: 'https://http2.mlstatic.com/D_NQ_NP_930359-MLA52641822787_112022-O.jpg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
  {
      id: 8,
      name: 'Surface',
      brand: 'Microsoft',
      price: 964,
      image: 'https://cdn.cs.1worldsync.com/e5/9d/e59ded56-316c-480d-b5ba-fc64ff85cbc6.jpg',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi veritatis voluptate, iste voluptatem atque iure, repellendus voluptatibus asperiores.',
  },
]

export default products